version: "3.8"

services:

  item-db:
    container_name: item-db
    image: mongo:3
    ports:
      - "27020:27017"
    networks:
      - item-app-net
    volumes:
      - "app-db:/data/db"
    restart: on-failure

  item-app:
    container_name: item-app
    image: item-app:v1
    ports: 
      - "80:8080"
    networks: 
      - item-app-net
    depends_on:
      - item-db
    restart: on-failure

volumes:
  app-db:
    name: app-db

networks:
  item-app-net:
    name: item-app-net
    driver: bridge