apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: order
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  labels:
    account: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order
    spec:
      serviceAccountName: order
      containers:
      - name: order
        image: ghcr.io/yogiflogic/order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: AMQP_URL
            value: amqp://127.0.0.1:5672/"
        resources:
          requests:
            cpu: 200m
