apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-tier
  namespace: dicoding-ns
  labels:
    app: backend-app
    tier: backend-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      tier: backend-tier
  template:
    metadata:
      labels:
        app: backend-app
        tier: backend-tier
    spec:
      containers:
        - name: backend-container
          image: ghcr.io/yogiflogic/karsajobs:latest
          ports:
            - containerPort: 8080
              name: backendport
          resources:
            requests:
              memory: "512Mi"
              cpu: 200m
            limits:
              memory: "1Gi"
              cpu: "999m"
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_ROOT_PASSWORD