apiVersion: v1
kind: Service
metadata:
  name: backend-srv
  labels:
    app: backend-srv
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  selector:
    app: backend-app
    tier: backend-tier