#versi api yang digunakan pada pada manifest k8s
apiVersion: v1

#mendefinisikan jenis object k8s service
kind: Service

#metadata untuk service berisi key & value
metadata:
  name: backend-srv
  labels:
    app: backend-srv

#medefenisi spesifikasi service yang akan di buat seperti
# port/target port, type port, selector/ object yang di pilih / object yang di tuju dll
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  selector:
    app: backend-app
    tier: backend-tier