#!/bin/sh
version: 2.1
jobs:
  build:
    docker:
       - image: docker:dind
         auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
 
    steps:
      - checkout

      - run:
          name: whoami
          command: |
            whoami
            usermod -aG docker root
            systemctl status docker
            systemctl start docker
            ls -l /var/run/docker.sock
            chmod 666 /var/run/docker.sock

      - run :   
          name: export token
          command: export $CR_PAT

      - run :
          name: Run SH
          command: sh build_push_image_karsajobs.sh

      