version: 2.1
jobs:
  build:
    docker:
       - image: ubuntu:20.04
 
    steps:
      - checkout

      - run :   
          name: export token
          command: export $CR_PAT

      - run :
          name: Update & Upgrade APT
          command: apt update && Upgrade -y
      
      - run :
          name: Update & Upgrade APT
          command: ls
      