#!/bin/sh
version: 2.1
jobs:
  lint_dockerfile_hadolint:
    working_directory: /app
    docker:
       - image: yogiflogic/ubuntu-with-docker:v1
         auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

    steps:
      - checkout

      - run:
          name: Install Hadolint
          command: |
            apt install wget -y
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint

  test_app:
    working_directory: ~/test
    docker:
      - image: cimg/go:1.21-browsers
    steps:
      - checkout
      - run:
          name: Go Test
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    working_directory: /app
    docker:
      - image: yogiflogic/ubuntu-with-docker:v1
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

    steps:
      - checkout

      - run:
              name: Run SH
              command: sh build_push_image_karsajobs.sh

workflows:
  build_and_test:
    jobs:
      - lint_dockerfile_hadolint
      - test_app:
          requires:
            - lint_dockerfile_hadolint
      - build-app-karsajobs:
          requires:
            - test_app

#      - run:
#          name: Install Go
#          command: |
#            rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
#            export PATH=$PATH:/usr/local/go/bin
#            go version

#      - run:
#          name: Test APP Go
#          command: go test -v -short --count=1 $(go list ./...)


#      - run:
#          name: Run Container with Docker Socket
#          command: socat TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock &
#
#      - run:
#          name: Docker
#          command: |
#            pwd
#            whoami
#            docker container ls -a
#            docker images -a

#      - run :
#          name: export token
#          command: export $CR_PAT
#
#      - run :
#          name: Run SH
#          command: sh build_push_image_karsajobs.sh

      