version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      - run :   
          name: export token
          command: export $CR_PAT

      # - run :
      #     name: Update
      #     command: apt update -y
      
      # - run:
      #     name: Test Docker
      #     command: docker --version

      - run:
          name: Set Docker Socket Permissions
          command: whoami
      
      - run:
          name: cek semua
          command: env

      - run :
          name: Run SH
          command: sh build_push_image_karsajobs.sh


     # - run:
      #     name: Set Docker Socket Permissions
      #     command: sudo usermod -aG docker circleci

      