#!/bin/sh
version: 2.1
jobs:
  build:
    docker:
       - image: yogiflogic/ubuntu-with-docker:v1
         auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
 
    steps:
      - checkout

      - run :   
          name: export token
          command: export $CR_PAT

      - run :
          name: Run SH
          command: sh build_push_image_karsajobs.sh

      