version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      - run :   
          name: export token
          command: export $CR_PAT

      # - run :
      #     name: Update
      #     command: apt update -y
      
      # - run:
      #     name: Test Docker
      #     command: docker --version
      - run: 
          name: update && upgrade
          command: |
             apt update -y
             apt upgrade -y       
      - run:
          name: docker 1
          command:  apt list
      - run:
          name: docker 2
          command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - run:
          name: docker 3
          command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      - run:
          name: docker 4
          command: apt update
      - run:
          name: docker 5
          command: apt-cache policy docker-ce
      - run:
          name: docker 6
          command: apt install docker-ce
      - run:
          name: docker 7
          command: systemctl status docker
      - run:
          name: docker 8
          command: usermod -aG docker root

      - run :
          name: Run SH
          command: sh build_push_image_karsajobs.sh


     # - run:
      #     name: Set Docker Socket Permissions
      #     command: sudo usermod -aG docker circleci

      