version: 2.1
jobs:
  build:
    docker:
       - image: ubuntu:20.04
 
    steps:
      - checkout
      - run :   
          name: export token
          command: export $CR_PAT

      - run :
          name: Update
          command: apt update -y
      
      - run :
          name: Ls
          command: ls
      
      - run :
          name: Run SH
          command: sudo sh ./build_push_image_karsajobs.sh

      