version: 2.1
jobs:
  build:
    docker:
       - image: cimg/base:current
         auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
 
    steps:
      - checkout

      - run :   
          name: export token
          command: export $CR_PAT

      - run :
          name: Update
          command: sudo apt update -y
       
      - run :
          name: Run SH
          command: sudo sh build_push_image_karsajobs.sh

      