version: 2.1
jobs:
  build:
    machine:
       image: ubuntu-20.04
 
    steps:
      - checkout

      - run :   
          name: export token
          command: export $CR_PAT

      - run :
          name: Update
          command: apt update -y
      
      - run:
          name: Install Docker
          command: apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      
      - run :
          name: Run SH
          command: sh build_push_image_karsajobs.sh

      