version: 2.1
jobs:
  build:
    docker:
       - image: ubuntu:20.04
 
    steps:
      - checkout

      - run :   
          name: export token
          command: export $CR_PAT

      - run :
          name: Update
          command: apt update -y
      
      - run :
          name: Ls
          command: ls

      - run :
          name: Instal docker
          command: snap install docker
      
      - run:
          name: Set Docker Socket Permissions
          command: chmod 666 /var/run/docker.sock
      
      - run :
          name: Run SH
          command: sh build_push_image_karsajobs.sh

      