version: 2.1
jobs:
  build:
    machine:
      image: ubuntu:latest
      docker_layer_caching: true

    steps:
      - checkout

      - run :   
          name: export token
          command: export $CR_PAT

      - run :
          name: Update
          command: sudo apt update -y
      
      - run:
          name: Test Docker
          command: sudo docker --version

      - run:
          name: Set Docker Socket Permissions
          command: whoami
      
      # - run:
      #     name: Set Docker Socket Permissions
      #     command: sudo usermod -aG docker circleci

      - run :
          name: Run SH
          command: sudo sh build_push_image_karsajobs.sh

      