#!/bin/sh
version: 2.1
jobs:
  build:
    docker:
       - image: yogiflogic/ubuntu-with-docker:v1
         auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

    steps:
      - checkout

      - run:
          name: Cek Docker Version
          command: docker version

      - run:
          name: Install Hadolint
          command: |
            apt install wget -y
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - run:
          name: Lint Dockerfile with Hadolint
          command: /bin/hadolint Dockerfile

#      - run:
#          name: Install Go
#          command: |
#            rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
#            export PATH=$PATH:/usr/local/go/bin
#            go version

#      - run:
#          name: Test APP Go
#          command: go test -v -short --count=1 $(go list ./...)

#      - run:
#          name: Install socat
#          command: apt-get update && apt-get install -y socat
#
#      - run:
#          name: Run Container with Docker Socket
#          command: socat TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock &

#      - run :
#          name: export token
#          command: export $CR_PAT
#
#      - run :
#          name: Run SH
#          command: sh build_push_image_karsajobs.sh

      