#versi api yang digunakan pada pada manifest k8s
apiVersion: v1

#mendefinisikan jenis object k8s secret
kind: Secret

#metadata untuk secret berisi key & value
metadata:
  name: mongodb-secret
  namespace: dicoding-ns

#mendefinisikan type base64
type: Opaque

#medefinisikan data username dan password berupa key value dalam bentuk base64
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==

# jika ingin menyimpan informasi di properti password,
# Anda perlu mengubahnya menjadi base64 encoded secara manual terlebih dahulu.