apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb-label
spec:
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
      tier: mongodb-tier
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: mongodb
        tier: mongodb-tier
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: mongo:3
          name: mongodb
          envFrom:
            - secretRef:
                name: mongodb-secret
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value:  /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
            - name: config-volume
              mountPath: /config
            - name: secret-volume
              mountPath: /etc/mongo-credentials
              readOnly: true

      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
        - name: config-volume
          configMap:
            name: mongodb-config
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: secret-volume
          secret:
            secretName: mongodb-secret
            items:
              - key: MONGO_ROOT_USERNAME
                path: MONGO_ROOT_USERNAME
              - key: MONGO_ROOT_PASSWORD
                path: MONGO_ROOT_PASSWORD