apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb-service-label
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb