#versi api yang digunakan pada manifest k8s
apiVersion: v1

#mendefinisikan jenis object k8s persistent volume
kind: PersistentVolume

#metadata untuk persistent volume berisi key & value
metadata:
  name: mongodb-pv
  labels:
    type: local

#medefenisi spesifikasi PV yang akan di buat seperti
#kapasitas, access modes , storage , host path dll
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
---
#versi api yang digunakan pada manifest k8s
apiVersion: v1

#mendefinisikan jenis object k8s persistent volume claim
kind: PersistentVolumeClaim

#metadata untuk persistent volume claim berisi key & value
metadata:
  name: mongodb-pv-claim
  labels:
    app: mongodb-app

#medefenisi spesifikasi PVC yang akan di buat seperti
#volume mode, access modes , storage dll
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi