#versi api yang digunakan pada manifest k8s
apiVersion: v1

#mendefinisikan jenis object k8s configmap
kind: ConfigMap

#metadata untuk configmap berisi key & value
metadata:
  name: mongodb-config

# konfgurasi letak path configmap pada volume storage
data:
  #  string multiline (ditandai dengan “|”)
  mongo.conf: |
    storage:
      dbPath: /config
#  data-tier-64dd6c7fcc-m9ftw